name: 2nd workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code from gh
        uses: actions/checkout@v3
      - name: run test
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: get code from gh
        uses: actions/checkout@v3
      - name: deploy to server
        run: echo "deploying to server"